### ISSUE TITLE
[feature request] add namespace argument to hooks

### ISSUE THREAD

**Issue by pawelru** [daroczig/logger#137] opened 2024-01-25 16:33 UTC
I would like to register message / warning / error hooks for a given namespace with predefined layout / appender etc. Currently all the hooks are logging into the global.

**Comment by daroczig** [comment] 2024-02-29 20:29
Thanks for the feature request! As I am busy with other things, I don't think I have the time to work in this in the coming months, so I would highly appreciate if someone can come up with a PR -- so thus I'm now setting the related "Help wanted" label.

**Comment by daroczig** [comment] 2024-02-29 23:04
actually, this is a duplicate of #60

**Closed by daroczig** 2024-02-29 23:04 UTC
Labels: help wanted
