### ISSUE TITLE
activating `log_errors()` multiple times returns multiple lines of same error log

### ISSUE THREAD

**Issue by przell** [daroczig/logger#109] opened 2022-06-17 09:09 UTC
Hi, 
just came across that activating `log_errors()` multiple time multiplies the error messages.

```r
log_errors()
log_failure(stopifnot(1 ==2))
ERROR [2022-06-17 07:28:47] 1 == 2 is not TRUE
ERROR [2022-06-17 07:28:47] 1 == 2 is not TRUE
Error: 1 == 2 is not TRUE
log_errors()
log_failure(stopifnot(1 ==2))
ERROR [2022-06-17 07:29:07] 1 == 2 is not TRUE
ERROR [2022-06-17 07:29:07] 1 == 2 is not TRUE
ERROR [2022-06-17 07:29:07] 1 == 2 is not TRUE
Error: 1 == 2 is not TRUE
log_errors()
log_failure(stopifnot(1 ==2))
ERROR [2022-06-17 07:29:17] 1 == 2 is not TRUE
ERROR [2022-06-17 07:29:17] 1 == 2 is not TRUE
ERROR [2022-06-17 07:29:17] 1 == 2 is not TRUE
ERROR [2022-06-17 07:29:17] 1 == 2 is not TRUE
Error: 1 == 2 is not TRUE
```

**Comment by daroczig** [comment] 2024-02-29 23:29
Sorry for the long delay with getting back on this :disappointed: 
Thanks for the report! This seems to be a duplicate of #88, which was fixed a couple of months ago, so closing this. Please reopen if you see otherwise.

**Closed by daroczig** 2024-02-29 23:29 UTC
